// Mock data for Kaş Hotel Companion prototype
// All Turkish strings, all fake numbers — пока только для прогулки по экранам

export const USER = {
  name: "Murat Yılmaz",
  short: "Murat bey",
  initials: "MY",
  location: "Kalkan, Antalya",
  villas: 2,
  plan: "Olgun paket",
  planPrice: "$327/ay",
  accountantEmail: "ahmet.muhasebe@gmail.com",
};

export const TODAY = {
  greeting: "Günaydın",
  dateTR: "22 Nisan Salı",
  time: "08:14",
  summary: "3 aktif rezervasyon, 1 çakışma, 4 karar bekliyor.",
};

export const WIDGETS = [
  {
    id: "bookings",
    label: "Rezervasyonlar",
    value: "3 aktif",
    meta: "1 çakışma",
    metaStyle: "alert",
    icon: "bookings",
    route: "#/bookings",
    sparkline: [4, 5, 3, 6, 5, 7, 8, 6],
  },
  {
    id: "pricing",
    label: "Haftalık fiyat",
    value: "4 boş hafta",
    meta: "+%8 öneri",
    metaStyle: "ok",
    icon: "pricing",
    route: "#/pricing",
    sparkline: [120, 140, 135, 160, 155, 170, 180, 165],
  },
  {
    id: "tax",
    label: "Vergi eşiği",
    value: "KDV %82",
    meta: "~6 hafta",
    metaStyle: "warn",
    icon: "tax",
    route: "#/tax",
    gauge: 82,
  },
  {
    id: "bot",
    label: "Misafir bot",
    value: "14 mesaj",
    meta: "bugün otomatik",
    metaStyle: "ok",
    icon: "bot",
    route: "#/bot",
    sparkline: [2, 4, 3, 5, 7, 6, 9, 14],
  },
];

export const ALERTS = [
  {
    id: 1,
    kind: "critical",
    icon: "star",
    title: "Yeni 1★ yorum",
    body: "Bayram Villa · Google · «Havuz temiz değildi»",
    time: "12 dk önce",
    cta: "Özel yanıt yaz",
    route: "#/reviews",
  },
  {
    id: 2,
    kind: "warn",
    icon: "alert",
    title: "Platform çakışması",
    body: "Olive Suite · 28–30 Nisan Booking + Airbnb çift rezervasyon",
    time: "34 dk önce",
    cta: "Çöz",
    route: "#/bookings",
  },
  {
    id: 3,
    kind: "info",
    icon: "trending",
    title: "Sıralama düştü",
    body: "Bayram Villa · Booking Kalkan: 8 → 14 · komşu €12 indirdi",
    time: "1 sa önce",
    cta: "Fiyat öner",
    route: "#/pricing",
  },
  {
    id: 4,
    kind: "ok",
    icon: "check",
    title: "Fiyat güncellendi",
    body: "Olive Suite · 7 platformda yeni fiyat yayıldı",
    time: "3 sa önce",
    cta: null,
    route: null,
  },
];

export const VILLAS = [
  {
    id: "bayram",
    name: "Bayram Villa",
    location: "Kalkan · Kışla Mah.",
    image: "../images/hero.jpg",
    rating: 4.8,
    reviews: 127,
    rooms: 3,
    occupancy: 68,
    monthBookings: 11,
    platforms: ["Booking", "Airbnb", "Direct"],
    amenities: ["Havuz", "Deniz manzarası", "Wi-Fi", "Klima", "Terras", "Mutfak", "Ücretsiz park", "Pet dostu"],
  },
  {
    id: "olive",
    name: "Olive Suite",
    location: "Kaş · Küçükçakıl",
    image: "../images/hero.jpg",
    rating: 4.9,
    reviews: 84,
    rooms: 2,
    occupancy: 74,
    monthBookings: 9,
    platforms: ["Booking", "Airbnb"],
    amenities: ["Deniz manzarası", "Wi-Fi", "Klima", "Jakuzi", "Teras"],
  },
];

export const BOOKINGS = [
  { id: "b1", guest: "Richard Thompson", villa: "Bayram Villa", platform: "Booking", dates: "24–28 Nis", nights: 4, total: "€680", flag: "🇬🇧", status: "ok" },
  { id: "b2", guest: "Anna Schmidt", villa: "Bayram Villa", platform: "Airbnb", dates: "28–30 Nis", nights: 2, total: "€340", flag: "🇩🇪", status: "conflict" },
  { id: "b3", guest: "David Price", villa: "Olive Suite", platform: "Booking", dates: "28–30 Nis", nights: 2, total: "€520", flag: "🇬🇧", status: "conflict" },
  { id: "b4", guest: "Marco Ricci", villa: "Olive Suite", platform: "Direct", dates: "2–9 May", nights: 7, total: "€1 820", flag: "🇮🇹", status: "ok" },
  { id: "b5", guest: "Emma Lewis", villa: "Bayram Villa", platform: "Booking", dates: "5–12 May", nights: 7, total: "€1 190", flag: "🇬🇧", status: "ok" },
  { id: "b6", guest: "Yuki Tanaka", villa: "Olive Suite", platform: "Airbnb", dates: "14–21 May", nights: 7, total: "€1 890", flag: "🇯🇵", status: "ok" },
  { id: "b7", guest: "Sophie Martin", villa: "Bayram Villa", platform: "Direct", dates: "22–29 May", nights: 7, total: "€1 260", flag: "🇫🇷", status: "ok" },
];

export const CONFLICT = {
  title: "Aynı tarih, iki platform",
  dates: "28–30 Nisan",
  villa: "Olive Suite",
  options: [
    { id: "o1", label: "Airbnb'yi iptal et", sub: "Anna Schmidt · €340 · Booking cezası yok", preferred: false },
    { id: "o2", label: "Booking'i iptal et", sub: "David Price · €520 · Airbnb superhost riski", preferred: false },
    { id: "o3", label: "Bayram Villa'ya taşı", sub: "28–30 Nis boş · 3 km fark · misafire bilgi", preferred: true },
  ],
};

export const PRICING_WEEKS = [
  {
    id: "w1",
    label: "Bu hafta",
    dates: "21–27 Nis",
    occupancy: 45,
    current: 170,
    suggested: 155,
    delta: -9,
    reason: "Düşük doluluk · komşular €148–165 aralığında · sezon başı",
    competitors: [148, 155, 162, 165, 170],
    applied: false,
  },
  {
    id: "w2",
    label: "Önümüzdeki hafta",
    dates: "28 Nis – 4 May",
    occupancy: 72,
    current: 170,
    suggested: 195,
    delta: 15,
    reason: "Yüksek doluluk · 1 Mayıs tatili · komşular zaten €190+",
    competitors: [185, 190, 195, 198, 210],
    applied: false,
  },
  {
    id: "w3",
    label: "2 hafta sonra",
    dates: "5–11 May",
    occupancy: 38,
    current: 170,
    suggested: 160,
    delta: -6,
    reason: "Ortalama talep · yakın rezervasyon az · fiyat esnek",
    competitors: [155, 158, 162, 165, 168],
    applied: false,
  },
  {
    id: "w4",
    label: "3 hafta sonra",
    dates: "12–18 May",
    occupancy: 84,
    current: 170,
    suggested: 215,
    delta: 26,
    reason: "Çok yüksek talep · Kalkan yat fuarı · rakipler €220'ye gidiyor",
    competitors: [205, 215, 220, 225, 230],
    applied: false,
  },
];

export const TAX_THRESHOLDS = [
  {
    id: "kdv",
    label: "KDV eşiği",
    sub: "Değer eklenen vergisi",
    current: 575000,
    limit: 700000,
    unit: "₺",
    percent: 82,
    weeksLeft: 6,
    trend: "yükselişte",
    note: "Bu tempoda 6 hafta sonra KDV mükellefi olursun. Şimdi bir fatura tersine çevirmek mümkün.",
  },
  {
    id: "gelir",
    label: "Gelir vergisi dilimi",
    sub: "%27'den %35'e geçiş",
    current: 820000,
    limit: 990000,
    unit: "₺",
    percent: 83,
    weeksLeft: 8,
    trend: "yükselişte",
    note: "8 hafta içinde %8 daha yüksek dilime geçersin. Kişisel/şirket ayrımı düzeltilebilir.",
  },
  {
    id: "konaklama",
    label: "Konaklama vergisi",
    sub: "Aylık beyan · ayın 26'sı",
    current: 11200,
    limit: 14000,
    unit: "₺",
    percent: 80,
    weeksLeft: 1,
    trend: "aylık reset",
    note: "Bu ay beyana 4 gün kaldı. Şablon hazır, tek tuş muhasebeciye gider.",
  },
];

export const BOT_CONVOS = [
  {
    id: "c1",
    guest: "Richard",
    flag: "🇬🇧",
    villa: "Bayram Villa",
    turns: [
      { from: "guest", text: "Good morning — what time is breakfast?" },
      { from: "bot", text: "Günaydın Richard bey! 07:30'da teraste, 10:30'a kadar. İngiliz kahvaltısı da var." },
      { from: "guest", text: "Perfect. And beach distance?" },
      { from: "bot", text: "Kaputaş Plajı 4 dk arabayla, Kalkan limanı 3 dk yürüyüş. Taksi ister misin?" },
    ],
    status: "handled",
  },
  {
    id: "c2",
    guest: "Anna",
    flag: "🇩🇪",
    villa: "Olive Suite",
    turns: [
      { from: "guest", text: "Wann ist der Pool sauber?" },
      { from: "bot", text: "Havuz her sabah 07:00–08:00 arası temizleniyor. Şu an kullanıma hazır, Anna hanım." },
      { from: "guest", text: "Danke. Gibt es ein gutes Fischrestaurant?" },
      { from: "bot", text: "İki öneri: Mehmet'in Yeri (300m, balık) veya Limanağzı (tekne, 15 dk). Rezervasyon yapmamı ister misin?" },
    ],
    status: "handled",
  },
  {
    id: "c3",
    guest: "Marco",
    flag: "🇮🇹",
    villa: "Olive Suite",
    turns: [
      { from: "guest", text: "Ciao, il Wi-Fi non funziona" },
      { from: "bot", text: "Ay, üzgünüm Marco. Şifre: olive2026. Router terasın girişinde, kırmızı ışık yanıyor mu?" },
      { from: "guest", text: "No, niente luce" },
      { from: "bot", text: "Anladım — Murat bey'e ilettim, 10 dk içinde orada olacak. Sorry for the inconvenience." },
    ],
    status: "escalated",
  },
];

export const REVIEWS = [
  {
    id: "r1",
    stars: 1,
    platform: "Google",
    guest: "Y. Özdemir",
    when: "12 dk önce",
    villa: "Bayram Villa",
    text: "Havuz temiz değildi, çöp kutusu doluydu. Personel uyarıdan sonra geldi.",
    draft: "Y. bey, yorumunuz için teşekkür ederiz — özellikle çöp ve havuz konusunda. Şu an temizlik programımızı gözden geçiriyoruz. Bugün size özel bir brunch önermek istiyoruz — kabul eder misiniz? Saygılarımla, Murat.",
    flag: "new",
  },
  {
    id: "r2",
    stars: 5,
    platform: "Booking",
    guest: "Richard T.",
    when: "2 sa önce",
    villa: "Bayram Villa",
    text: "Perfect sea view, amazing host. Will return next summer!",
    draft: "Richard bey, çok teşekkür ederiz! Gelecek yaz için sizi yeniden beklemek bizi mutlu eder — erken rezervasyona %10 indirim yapalım mı?",
    flag: null,
  },
  {
    id: "r3",
    stars: 4,
    platform: "TripAdvisor",
    guest: "Helena K.",
    when: "dün",
    villa: "Olive Suite",
    text: "Lovely location, Wi-Fi was slow one evening.",
    draft: "Helena hanım, teşekkürler! Wi-Fi sorunundan haberdarım — router yenilendi. Bir dahaki ziyaretinizde farkı göreceksiniz.",
    flag: null,
  },
  {
    id: "r4",
    stars: 5,
    platform: "Airbnb",
    guest: "Anna S.",
    when: "2 gün önce",
    villa: "Olive Suite",
    text: "Absolut traumhaft. Jeder Morgen ein Geschenk.",
    draft: "Anna hanım, teşekkürler — 'Geschenk' kelimesi bizi çok mutlu etti. Eylül'de yine bekleriz!",
    flag: null,
  },
  {
    id: "r5",
    stars: 2,
    platform: "Booking",
    guest: "M. Johnson",
    when: "3 gün önce",
    villa: "Bayram Villa",
    text: "Description said 5 minutes to beach, it was 20.",
    draft: "M. bey, haklısınız — açıklamamızda düzeltme yaptık. Bir dahaki konaklamada transferi bizden, size özel.",
    flag: null,
  },
  {
    id: "r6",
    stars: 5,
    platform: "Google",
    guest: "Fatma Y.",
    when: "4 gün önce",
    villa: "Olive Suite",
    text: "Bayıldık. Kahvaltı bir harika. Personel çok ilgili.",
    draft: "Fatma hanım, teşekkürler! Kahvaltı ekibimize iletiyoruz, motive olacaklar. Yakında sizi tekrar görmek isteriz.",
    flag: null,
  },
];

export const ONBOARDING = [
  {
    id: 1,
    image: "../images/insight.jpg",
    title: "Çok platform, tek panel.",
    body: "Booking, Airbnb, direkt rezervasyon — hepsi bir ekranda. Çifte rezervasyon sıfır.",
  },
  {
    id: 2,
    image: "../images/pain.jpg",
    title: "Haftalık fiyat akıllı olur.",
    body: "Her Pazar önümüzdeki 4 hafta için fiyat önerisi gelir. Tek tuşla uygula.",
  },
  {
    id: 3,
    image: "../images/shift.jpg",
    title: "Vergi eşikleri sürpriz değil.",
    body: "KDV, gelir, konaklama — hepsi izleniyor. Geçmeden önce haber verir.",
  },
];

export const NAV = [
  { id: "home", route: "#/home", label: "Ana sayfa", icon: "home" },
  { id: "bookings", route: "#/bookings", label: "Rezervasyon", icon: "bookings" },
  { id: "pricing", route: "#/pricing", label: "Fiyat", icon: "pricing" },
  { id: "bot", route: "#/bot", label: "Misafir", icon: "bot" },
  { id: "more", route: "#/more", label: "Daha", icon: "more" },
];
